### ISSUE TITLE
Run 1 Risk: SNe may not make good CoaddSources

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/Twinkles#146]
@SimonKrughoff 

@rbiswas4 and I are thinking about what we expect the Run 1 light curves to look like. If they are coming from forced photometry of CoaddSources, there are risks, including:
- SNe might appear too faint in Coadd Image to be detected, even though the SNR at the peak of the light curve may be 10 sigma
- CoaddSources might land on the SN host galaxy, not the SN. And if this galaxy is not classified as point-like, might it not have forced photometry done on it?

Given this: is there an easy way that we could force (!) the forced photometry to take place at (Ra,Dec) positions of our choice, not the CoaddSource finder's?

Note that these risks will go away when we switch to detecting SNe on the difference images.

**Comment by rbiswas4** [comment]
As opposed to the much harder case of real data, we know many things about the data underlying the images here, we could fix some of the things we might normally be worried about in real data, and therefore test other modes independently. It would be great to figure out how to run some of DM analysis tools in this mode.

**Comment by SimonKrughoff** [comment]
I think we can create SourceCatalogs containing the locations of the SNe to seed forced photometry.  I'll look into that next week.

**Comment by drphilmarshall** [comment]
That sounds like very useful functionality!

**Comment by drphilmarshall** [comment]
I think this is something we should shoot for in Run 2 - unless it's so easy we could just do it for Run 1.1...

**Comment by drphilmarshall** [comment]
Adding this to the set of issues relating to the Twinkles Design Note - this is part of the justification for image differencing.

**Comment by drphilmarshall** [comment]
Closing this out: we're going for image differencing!
