### ISSUE TITLE
Data Catalog user guide

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/Twinkles#148]
@tony-johnson @TomGlanzman Can you point me to the SRS data catalog user guide please? While downloading the first Run 1images I found a number of features of the system non-intuitive - which I think means we need to provide some user support. To me. ;-) Thanks!

**Comment by brianv0** [comment]
Hi Phil,

Is there anything specific you need help with? We have some user guides, but most of them target registering and querying the data catalog, and not so much about using the web interface.

By the way, there is quite a bit of work going on in the data catalog on a next generation version. This work includes an overhauled web UI, a python library (which Tom might actually be using) and a CLI based on it, and other features. I could show you a development version of that interface, but it's not stable nor at feature parity with the current interface yet, so we don't really like to advertise it that much.

**Comment by drphilmarshall** [comment]
A basic user guide would be good - I found it hard to download the second file, because the "download" link gave me a second copy of the java app, which then did not open and run. Then, beyond quick look exercises like the one I went through, I'd like to know how to query the catalog for data from python using urllib or similar. Thanks!

**Comment by drphilmarshall** [comment]
Also, when trying to "add" more files to download in the java app window, it asked me for a URL - but I didn't know the URL in the first place (otherwise I would have just curl'ed it ;-) )

**Comment by drphilmarshall** [comment]
Canning this, as our recommended route is to use the `Pserv` db at NERSC directly.
