### ISSUE TITLE
What SN Rate should we use for the next Twinkles Run?

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/Twinkles#241]
We would like to have a reasonable sample of supernovae in Twinkles and in each image.

We would like a total of 1000 SN Ia lightcurves to analyze.  For a one year run, that seemed like on order 100 SN/image.

We chose 100 SNe at SNR>5 for the first Run with a flat redshift distribution.  That resulted in far too many supernovae.

@rbiswas4 Given the experience in the first run, and your expertise in thinking about simulating supernovae, please think about what you would recommend for our next run, and develop a specific proposal along with its expected performance and consequences.

**Comment by rbiswas4** [comment]
> We chose 100 SNe at SNR>5 for the first Run with a flat redshift distribution. That resulted in far too many supernovae.

Actually, we targeted 100 SNe with SNR > 5 *in that visit*, while the true number of SN showing up on that visit (with lower SNR) could (and would) be much higher. This is what increases the number to such values.  (details in https://github.com/rbiswas4/sgi/blob/master/src/Twinkles_SimulatedSN_Setup.ipynb, https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/doc/SNSimDocumentation/fiveSigmaDepths.ipynb).


But, yes, we should redesign for the next run, and I am happy to work on developing specific proposals. The point is we can get 1000 light curves in many different ways, and we should ask what is the best way for us. I think we should do that by (a) answering a series of questions and (b) having specific tests to ensure that the proposal does not suffer from defects we are afraid of. (Both a, and b could take contributions from anyone, and I will start with those on my mind).  

First, something to just get some intuition on the numbers might be this plot showing the cumulative numbers of SNIa expected in an LSST field per year (in units of 1000). This does not have any information about observations/detections etc. It simply says that within a time window of 1 year (10 year in the lower plot) the sky corresponding to an LSST field has this many SN go off at redshift below z.

![cumulativesn](https://cloud.githubusercontent.com/assets/2281358/15263111/e0553ac8-191b-11e6-839b-bc41838b0ded.png)

- Assuming that we lose half of the years for season, for a ten year survey we get 1000 light curves with z ~<  0.4 in a ten year survey with the natural rate. If we need to do this in 1 year, we need to go all the way up to z ~ 1.2. So, we could potentially do 1000 light curves with just the usual physical rate of SN.
- If we use the DDF cadence, maybe z~1.2 is possible, but with the Twinkles 1 cadence (which is somewhat better than WFD but has much lower effective exposure time that DDF), this may be harder, but we should certainly be able to do z~0.4.

## Questions:
- Duration of the survey
     - [ ] 1 year 
     - [ ] 10 year 
     - [ ] other
- Cadence of the survey:
    - [ ] Twinkles 1 like 
    - [ ] DDF 
- Do we want to do cosmology-like studies where we care about the distribution of parameters of the SN that are detected or are we happy if we are able to do light curve fits
- Do we want a certain number of high redshift SN in the sample?
- Do we want a certain number of SN with a number of very high SNR points (for example to be confident of being able to run DM processing on these, or calibrate the results of lower SNR SN against these)?
- Do we want a certain number of SN in different galaxy environments ? 


## Tests to ensure that undesirable qualities are not there

- Multiple SN not in the same galaxy.
- Multiple SN not in the same line of sight.

**Comment by drphilmarshall** [comment]
@rbiswas4 Let's close this, but remember later that you had some good material for the design note in here.
