### ISSUE TITLE
Make ipython demo notebook run remotely at NERSC 

### ISSUE THREAD

**Issue by jbkalmbach** [LSSTDESC/Twinkles#260]
Cross-Repo issue with DarkEnergyScienceCollaboration/Monitor#28. Just wanted to add it here too so people would see it.

**Comment by drphilmarshall** [comment]
Thanks Bryce!

**Comment by drphilmarshall** [comment]
Hey @jbkalmbach - @djbard just pointed out that NERSC has a JupyterHub, check it out:

> We already have Jupyter supported at NERSC - and we use it extensively! See: 
>
http://www.nersc.gov/users/data-analytics/data-analytics/web-applications-for-data-analytics/
>
https://ipython.nersc.gov/hub/login

Have you tried using this?

**Comment by jbkalmbach** [comment]
@drphilmarshall cool. Just gave it a try. Looks promising. I'll try to get the monitor demos setup and running with it.

**Comment by drphilmarshall** [comment]
Sweet! I need to telephone them to get my account active: should be able to
do this tomorrow.

**Comment by djbard** [comment]
Having said that, jupyter may not be reliably available right now as it was running on a Cori node - which is down for integration. It'll be more reliably up in a couple of weeks. 
Your NERSC account, @drphilmarshall? It's active (according to [NIM](https://nim.nersc.gov/)) - if you just need to reset your password you can do it from the [NIM](https://nim.nersc.gov/) site.

**Comment by jbkalmbach** [comment]
@rbiswas4 and I had a productive conversation with @rcthomas and @djbard from NERSC today. We now have a way to use jupyter-dev.nersc.gov to run notebooks with the LSST stack setup. I will write up some notes and post them so others can try.

**Comment by jbkalmbach** [comment]
Instructions added into Monitor repo [here](https://github.com/LSSTDESC/Monitor/blob/master/doc/setup_jupyter-dev.md).
