### ISSUE TITLE
Use tagged releases of DM stack and sims tools

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/Twinkles#289]
In #275, @rbiswas4 wrote:

> This is about the installation instructions here for the conda build and the issue is about having
> both DM and Sims stacks work on the same installation using updates.
> 
> I had a short discussion about the installation instructions with @danielsf as I was not entirely sure about this. The current installation uses the LSST releases.  However, these releases have a cadence of either 1 or 2 a year. This means that in the intermediate time, there will be updates to the DM and definitely the SIMs stack that will be essential for Twinkles users. This was the rationale between Scott creating tagged releases of both DM and sims at a much higher cadence.
> 
> The instructions for installing these release are at https://confluence.lsstcorp.org/display/SIM/Catalogs+and+MAF. The main change for these is the conda channel. @danielsf is the expert to talk to and can tell you more about the cadence of this set.

I think this means we need to upgrade our installation notes, following the instructions in the link that Rahul provides. I can try and do this at some point.

**Comment by heather999** [comment]
I just want to clarify one point with @danielsf and @rbiswas4, in your humble opinions, should we just use the sims channel exclusively (http://conda.lsst.codes/sims) and completely ignore the "official" DM channel (http://conda.lsst.codes/stack) for installing both lsst-sims as well as lsst-apps?

**Comment by danielsf** [comment]
Yes.  We will always make sure that there is an installation of lsst_apps on the sims channel and (this being the important part) that it is built against the same DM packages as the installation of lsst_sims.

**Comment by heather999** [comment]
Ok I took a first swing at modifying the text.

Shall we also heed @danielsf's comment on #275?

> Historically, adding LSST setup commands to ~/.bash_profile has caused problems for people. 
> Setting up the LSST stack usually involves using a specific installation of python, which is not
> always the user's default preferred python installation. I would instead recommend that they copy > those commands to an setUpLSST.sh script, and just source that script whenever they want to run
> the LSST stack.

I'd be inclined to stick with a clean default environment and then have people set things up for their daily work.

There's also a little trick you can use in conda which will avoid the need to interactively type 'y' at times during the installation:

`conda config --set always_yes yes`

**Comment by drphilmarshall** [comment]
That sounds good to me, Heather. Should a setUpLSST.sh script be checked in
to the Twinkles repo and also the cookiecutter template project?

**Comment by cwwalter** [comment]
(t)csh forever! :)

You might want to also include one who use that family for their main login shell.. For example this is what I use to setup on my laptop:

`# For DS9 etc
set path = (/Users/walter/LSST/bin $path)

# For Anaconda
set path = (/Users/Walter/LSST/Anaconda/bin $path)

# For DM
source /Users/walter/LSST/Anaconda/bin/eups-setups.csh 
`
Also, get off my lawn :)

**Comment by heather999** [comment]
So perhaps we can show examples for both bash and c-shell and leave it at that.

**Comment by heather999** [comment]
We could provide a setupLSST.sh (and setupLSST.csh) and yes - I need to go back and look at that cookie-cutter example, @drphilmarshall 
Frankly, we could provide a script that does the lsst-apps, lsst-sims installation and sets up the environment too - but perhaps that's overkill, as a full install shouldn't be necessary so often.

**Comment by drphilmarshall** [comment]
@heather999 Anything you can do to remove the "workaround" section of the "getting started" instructions to enable `tcsh` users like me to get set up with the correct builds would be much appreciated!

**Comment by drphilmarshall** [comment]
I've more or less resigned myself to switching to `bash`, so will close this now and re-issue cries for help another time. Thanks all!
