### ISSUE TITLE
DIAObject production? 

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/Twinkles#296]
@ctslater just gave a nice talk about Level 1 analysis here at the DM plenary session at the Tucson LSST PCW. His slides are [here](https://project.lsst.org/meetings/lsst2016/sites/lsst.org.meetings.lsst2016/files/LSST2016%20-%20L1%20in%20depth.pdf), and they include a nice flow chart of the planned image differencing pipeline. He has some nice results on treating correlated noise during the DIASource detection process, which look relevant for us! Also relevant: he has a working Level 1 pipeline, which we should look at and perhaps adopt.

Colin: are you working with `DIAObjects` at all? I missed the part where you said where you were getting your positions from for your forced photometry. Here in Twinkles we are trying to make realistic LSST light curves of SNe so we can test how well they work for cosmology, and so your experience is very relevant for us. Thanks!

**Comment by ctslater** [comment]
We do not currently have the matching/association pipeline for DIA Sources. I did not need to match DIA sources between visits; the sources that were fed into force photometry were just all of the DIA sources from that same visit, not between visits. When/how we will develop the association pipeline is something that @SimonKrughoff can speak more to. It is a significant gap in our codebase.

I'm happy to share any other experience with the Twinkles effort.

**Comment by drphilmarshall** [comment]
Thanks Colin! I thought that would be the case but just wanted to check. We
have used CoaddSources so far, but will need a different mechanism when we
start doing image differencing. One possibility could be to make a
"variability coadd" out of the difference images, and then generating
"CoaddSources" from that. Alternatively we could bite the bullet and
implement a source associator, with some DM guidance.

**Comment by djreiss** [comment]
Please count me in on this discussion. I've had to "hack" a DIA source matcher for some of my recent analyses and would like to contribute to a more final solution.

**Comment by drphilmarshall** [comment]
Welcome, David! In the course of your hacking did you have any interaction
with Robert Lupton and his group? I'd like to get a sense of what working
on a more final solution to the DIAObject production problem would entail.
In an ideal world I guess we'd submit a bang-up pull request to the DM repo
and accelerate the project in the process...

**Comment by drphilmarshall** [comment]
@SimonKrughoff I just checked the Cookbook folder, and I don't see a write-up of your simple DIAObjectMaker that you put together at the Hack Week in November. We'll need that soon, to aggregate the DIASources that are about to appear once the templates are made! It could be a very short recipe - or a final section in the coadd diffim recipe, whatever's easiest for you.

**Comment by drphilmarshall** [comment]
Ah! I just found it in PR #412, now merged. @djreiss you might be interested to take a look at what we are doing here,  ["Emulating the Level 1 Reprocessing of DIAObjects"](https://github.com/LSSTDESC/Twinkles/blob/master/doc/Cookbook/Reprocessed_DIAObjects_Recipe.md)  Thanks Simon!
