### ISSUE TITLE
Twinkles 1 PhoSim Pipeline Review

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/Twinkles#323]
@DarkEnergyScienceCollaboration/twinkles 

At last week's meeting we discussed "pilot error", and how it can be avoided by the designers of a pipeline carefully checking the pipeline before it is run. For us, this means carefully checking the [Sims Recipe in the Cookbook](https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/doc/Cookbook/Sims_Recipe.md), all the PhoSim configuration files, and the instance catalog generation code. Our goal is to start the Run 3 PhoSim jobs on Friday 30th September, so how about we schedule a review of all the above on the Monday before that, September 26th - or a day close to that day. 

I think we need @wmwv to review the SN parts of the instance catalog generation, @drphilmarshall to review the SL parts of the instance catalog generation, both of those people plus @SimonKrughoff and @sethdigel to review the PhoSim configuration and Sims Recipe.

What do you think? Seth, Michael, Simon, can you make time on that Monday to sign off on the Run 3 sims pipeline? I guess we will need to go through it ourselves first before meeting up - is it going to be possible to do that in the morning, and then meet in the afternoon, or something? @jchiang87 please suggest modifications to the design of the review while we check our schedules! :-)

**Comment by jchiang87** [comment]
Although not really an item for the review process, I think it would be wise to have a script that checks the input values of physics parameters in our instance catalogs against either the FITS header keyword values in the phosim output files or the "log" output from phosim which reports the parameters that were used.   Otherwise, we have to check these by eye (and/)or risk having incorrect default values being silently used, as occurred for the altitude in Run1.1.

The review should, of course, also include the workflow scripts that execute the Level 2 tasks.   In addition, since we are making approximations on the simulation side, the **default** configs in those Level 2 tasks should also be explicitly checked against those approximations.

**Comment by drphilmarshall** [comment]
While checking the input values of physics parameters against the PhoSim output image headers is something we'll want to do as validation, printing the input values of physics parameters and comparing them with a) the PhoSim recipe and b) our expert brains seems like a critical part of the review. Perhaps we should start the script you suggest now, and teach it do the simple printout first so that we have something to look at next week. Would you mind issuing and assigning this, please Jim? I'm not sure who is best placed to write this script. (And should it, in fact, be a worker class, so that we can `from desc.twinkles import Validator` and then summon a `worker = Validator()` and demand that the `worker.report_phosim_physics_inputs()`?)

Also: whats the best way to expose all the defaults that the pipelines are using? Is this a manual look-up, or could a `Validator` do something clever when reporting?

@wmwv @SimonKrughoff @sethdigel I suggested that we 4 carry out a pipeline review early next week. How about Tuesday morning PDT? @TomGlanzman @rbiswas4 @danielsf @jbkalmbach will the cookbook recipe, catalog generation code, phoSim pipeline tasks and configuration files be ready to review at that point? Please advise! :-)

@tony-johnson Jim is suggesting that we review the basic (ie Run 2) DM Level 2 pipeline at the same time as reviewing the PhoSim pipeline, next week. I guess all this code is checked in and ready to be looked at, right?

**Comment by TomGlanzman** [comment]
Next Tuesday is too early for me as I have not integrated the ICgen code into the phoSim workflow.  Also, there is some possibility that my on-call jury duty responsibility will interfere with the day.  I suggest that time early for me would be a few days after the arrival of the ICgen code.

**Comment by rbiswas4** [comment]
>  a script that checks the input values of physics parameters in our instance catalogs against either the FITS header keyword values in the phosim output files or the "log" output from phosim which reports the parameters that were used. Otherwise, we have to check these by eye (and/)or risk having incorrect default values being silently used, as occurred for the altitude in Run1.1.

@jchiang87 I agree with this. Could you please link an example of a phosim output file or the header variable names, so that I can check that we have the inputs from the 'truth' side and have that part of the code ready?

**Comment by rbiswas4** [comment]
will the cookbook recipe, catalog generation code, phoSim pipeline tasks and configuration files be ready to review at that point? Please advise! :-)

The instance catalog and inputs and cookbook recipes should be ready. This does not include things @TomGlanzman talks about.

**Comment by SimonKrughoff** [comment]
@drphilmarshall What do you want to do about image differencing in the cookbook recipe?  I am not going to have time to nail that down concretely between now and then.  Is it still worth doing the review?

**Comment by rbiswas4** [comment]
There is a decision that would be useful to take:
In the current layout of the script: two things are created:
- phosim instance catalogs 
- SEDS for SN


For the analyses that we want to do, we know that we want to have the information in these catalogs:
- phosim Instance Catalogs
- catsim instance catalogs (not necessarily created at phosim generation time and will take extra time)
- phosim centroid files (after generation)
saved to databases. 

Do we want to ingest this information 
1. by running through the pointing loop  separately?
2. using the saved phosim instance catalogs + generating catsim instance catalogs later ?
3. .ingesting the phosim instance catalogs + phosim centrod files as we go in the current loop?
4. do everything in the current loop?


I don't care, but we will need to do all of these for the analyses:
This is probably a question for @TomGlanzman @jchiang87 and @tony-johnson

**Comment by drphilmarshall** [comment]
@SimonKrughoff How about we review the "baseline" DM Level 2 pipeline,
which just does what we did in Run 2, and plan on executing that in
October, at least up to for DR2 (one year - DR1 is after 6 months, I
remembered the other day!)?

Then, when image differencing is implemented and we are ready to re-run the
DM Level 2 pipeline, we could review that pipeline in the context of what
we know went into the sims. That follow-up run would be Run 3.1 (or
something).

The point is that we need Level 2 products to work on in November, not
least to develop the image differencing; but we may not need all that many.
You might wonder, why not just develop against Run 1.1? Its because the
science inputs will change, and we need to be into full data generation
mode so that eventually we can complete the whole tiny survey.

How does the above plan sound? Criticism and iterations welcome :-)

**Comment by TomGlanzman** [comment]
@rbiswas4 are you suggesting some/all of these steps be incorporated into the phoSim workflow?

**Comment by rbiswas4** [comment]
I am only stating the possibilities, to make sure all of us are aware of these steps, and the possibility that we could run all of them together. I don't know what is better for the workflow.

**Comment by jchiang87** [comment]
@rbiswas4 I'm a bit confused by the steps you describe.  What are the "catsim instance catalogs"?  Have we generated those before?  Regarding the phosim centroid files, I think those would be better to be ingested into db tables separately from the phosim execution pipeline.  Also, I don't think we've even discussed at any length what those tables should contain.

**Comment by rbiswas4** [comment]
> @rbiswas4 I'm a bit confused by the steps you describe. What are the "catsim instance catalogs"? Have we generated those before? 

No. But I think we should in order to study matches with the truths.  But perhaps, we can do this at a separate step.
> Also, I don't think we've even discussed at any length what those tables should contain.
I agree this is another good reason in favor of doing that `after` we start generation of phosim catalogs. Maybe we should start a discussion during the next meeting of how far we want to go (I guess the main reason to not store everything is disk resources)

**Comment by drphilmarshall** [comment]
OK: Pipeline Review Preparation. Here are the notes from our Sep 29th weekly meeting:

Materials to be reviewed are:

* Sims Cookbook Recipe (Author: Scott)
* Input catalog generation code (catalogs include catsim instance, phosim instance, phosim centroid, and so code includes treatment of lens sprinkling, SNe, and OpSim) (Author: Rahul et al)
* PhoSim pipeline tasks and configuration files, including default values  (Author: Tom)
* DM Level 2 Cookbook Recipe (still without image differencing, for now)  (Author: Simon)
* DM Level 2 pipeline tasks and configuration files (Author: Tony)

**When can all this be prepared by?** Simon has limited availability next week, so we will plan out time around him. He will provide a short list of windows, which we will promptly doodle for. 

**What needs to be done in order for the reviewers to be walked through it?**  We need a review page where links to each piece of material is provided. Phil and Jim will design this. 

**How long should we assign to this important review meeting?** An hour in person might be enough, especially if some work has been done offline first.

**Who needs to be at the review?** Rahul, Jim and Tom can represent the coding, Phil, Simon, Jim  and Seth can act as reviewers. Scott, Bryce, and Tony can help by providing links to the pipeline materials, which must all be up to date and ready to run. 
 

I will now make some sub-issues...

**Comment by SimonKrughoff** [comment]
As I mentioned on the call, I think I'll probably know better what my windows will be on Monday afternoon.

**Comment by jchiang87** [comment]
@drphilmarshall Run3 phosim generation is already/being done.  So closing.
