### ISSUE TITLE
Schedule the Pipeline Review

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/Twinkles#331]
@SimonKrughoff can you please let us know your short list of hour-long windows next week? We will then promptly doodle them. Thanks!

Attn: @sethdigel @jchiang87 @rbiswas4 @TomGlanzman

**Comment by SimonKrughoff** [comment]
@drphilmarshall it actually looks like my schedule is more flexible than I feared.  I can rearrange things before 3PM my time on all days this week except for noon on Wed.

**Comment by drphilmarshall** [comment]
Thanks Simon! I have made a doodle poll for us here, so we can choose a time on Thursday or Friday morning. All: please reply to this issue if you think the review materials will not be ready for review by any of those times!

http://doodle.com/poll/s8kyvg75e3d4y899

**Comment by drphilmarshall** [comment]
OK, thanks everyone: looks like Friday at 9 or 10am could work. However, @TomGlanzman reports that "the code for automatic instanceCatalog generation is not yet ready, and hence cannot yet be integrated into a pipeline task.  There is some DM code that may not yet be fully installed at SLAC (lsst sims) upon which this depends." So: let's take a look at this situation in our regular weekly meeting tomorrow, and decide then whether we can use an hour on Friday morning, or whether we should wait till next week. If we postpone, we can simply extend the same doodle poll.

**Comment by drphilmarshall** [comment]
Hi all: on Thursday we decided to try and re-schedule the Twinkles Run 3 pipeline review for this Wednesday, but we also heard that Tom will be unavailable this week due to the CHEP meeting in San Francisco - he won't now be able to prepare materials for a pipeline review until next week (he lost Friday to some urgent sensor work on the camera). He suggests that we "let the [new code] pieces come in, be assembled and tested, give a bit of time for a first look at some data samples, and then schedule a review." We just saw that we now have an instance catalog generator (excellent!), and so can start testing it at SLAC. Are there other things we can be reviewing and testing this week, before getting together for a review early next week?

**Comment by drphilmarshall** [comment]
OK, I have rejigged the doodle poll for the Twinkles Run 3 Pipeline Review to show next Thursday, October 20, as our preferred day - and opened up start times on the half hour as well as on the hour (as per Simon's comment). Let's budget for 90 minutes and aim to be done faster than that. Thoughts?

http://doodle.com/poll/s8kyvg75e3d4y899



PS. The answer to the previous comment in this thread was "yes", and work is proceeding.

**Comment by SimonKrughoff** [comment]
Did we schedule this meeting?  I don't see it on my calendar.
