### ISSUE TITLE
Install `twinkles_1` branch of `obs_lsstSim`

### ISSUE THREAD

**Issue by SimonKrughoff** [LSSTDESC/Twinkles#408]
@heather999 I mentioned it on the branch, but wanted to make sure there was an issue here.  Will you install a new version of `obs_lsstSim` with the `twinkles_1` branch please?  We'll need to update that occasionally, but I'll file new issues for that.

**Comment by SimonKrughoff** [comment]
Actually, the branch hasn't been pushed.  Give me a few minutes to do that.

**Comment by SimonKrughoff** [comment]
O.K. I've pushed the branch.  @heather999 feel free to update at your convenience.

**Comment by heather999** [comment]
Thanks, @SimonKrughoff, I'll see about installing the update.  @tony-johnson, @TomGlanzman are there plans to use an updated stack with this branched obs_lsstSim soonish?  I'm thinking to retain what is currently "v12_1 + slightly patched obs_lsstSim" at NERSC and introduce another tag with this new branch.  My intent would be to use the git commit as the tag name, just as we did last week when patching obs_lsstSim. So in effect, when setting up, we just set up lsst_apps as normal and then setup the desired tag of obs_lsstSim.  Does that sound plausible?

**Comment by danielsf** [comment]
In the event that managing the new `obs_lsstSim` proves annoying, I did cut a new version of `lsst_sims` and `lsst_apps` based on the most up-to-date sims stack and the latest DM weekly (w.2016.47).  This would resolve the `obs_lsstSim` problem (but mean we were not running DM release 12.1).

They can be installed via
`eups distrib install lsst_sims -t sims`
`eups distrib install lsst_apps -t sims`

**Comment by SimonKrughoff** [comment]
I'm afraid that, for the time being, we'll need to continue to use a v12_1 stack since that is where the branch of `obs_lsstSim` comes from.

@heather999 we do not need an updated stack, but we will need to rerun the DM processing with the new branch, if we want to do image differencing.

**Comment by heather999** [comment]
the twinkles_1 branch is now installed at NERSC on Cori (they had an outage that I wasn't expecting to last quite so long - but they came back online yesterday afternoon)
To use the update obs_lsstSim with DM v12_1, we can source the new setup script:
/global/common/cori/contrib/lsst/lsstDM/setupStack-12_1-Run3.1.sh
After doing that, the correct version of obs_lsstSim seems to be set up:
```
heatherk@cori02:/global/common/cori/contrib/lsst/lsstDM> eups list obs_lsstSim
   12.1         current b2294 b2296 fe_test v12_1
   12.1-1-gb840f6d
   12.1-10-g0a95c5d     setup
```

**Comment by heather999** [comment]
done!
