### ISSUE TITLE
Lost GitHub pages

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/Twinkles#427]
Now that we migrated to LSSTDESC, it seems our gh-pages branch has been lost as well as the accompanying website (https://darkenergysciencecollaboration.github.io/Twinkles/weekly/index.html) we had set up.  Digging around to see how to best recover..

**Comment by heather999** [comment]
Our new site is here: https://lsstdesc.github.io/Twinkles/
Trying to see if I can access our gh-pages branch.

**Comment by heather999** [comment]
Our gh-pages branch seems to still be intact, and is here: 
https://github.com/LSSTDESC/Twinkles/tree/gh-pages
However, I cannot access it via the GitHub web interface by choosing the "gh-pages" branch in the drop-down list.  It appears the link is pointing to the wrong place:

**Comment by heather999** [comment]
Things seem ok now.  Updated the Readme.md file and issued PR #428

**Comment by drphilmarshall** [comment]
Thanks Heather! This was a good catch. Ill come and review your PR now.
