### ISSUE TITLE
Use different name for two different coadds

### ISSUE THREAD

**Issue by SimonKrughoff** [LSSTDESC/Twinkles#438]
Right now we are using the same name for the deep and PSF homogenized coadds ('deep').  We should update the configs to call them two different things so we can have both in the same repo.  As it stands they will clobber each other.

**Comment by drphilmarshall** [comment]
Good catch!

**Comment by drphilmarshall** [comment]
@SimonKrughoff I think this can be closed: what names did you choose in the end, for the coadds being made in the two branches of the workflow?

**Comment by SimonKrughoff** [comment]
I agree this can be closed.  The full stack is called "deep" and the good seeing coadd is (not surprisingly) called "goodSeeing".
