### ISSUE TITLE
'u' band visits in Year 1

### ISSUE THREAD

**Issue by rbiswas4** [LSSTDESC/Twinkles#440]
There was a decision to build templates of Twinkles Run 1.3 visits from year 1. 
It has been reported (by @SimonKrughoff ?) that during year 1, Twinkles Run 1.3 has no visits in 'u' band, which would mean we cannot do u band difference images. However, checking on `minion_1016` for field 1427, we find that there are many (484)  'u' band visits (as for some reason u band tends to be extremely populous in deep drilling fields, 2nd highest visited band here). 

We need to understand what caused this difference, for example if all of the u band visits ended up on the list of long jobs, that we did not do.

**Comment by drphilmarshall** [comment]
From @SimonKrughoff on Slack:

> There was a run of OpSim that had no u-band images in year 1 (or thinking harder maybe it was none in year 10).  Anyway, there has been a lot of work in trying to flatten the filter coverage in time, so I was probably worrying about something that's long since been solved.

So let's close this out and wait and see if it's actually a problem! :-) Thanks both.
