### ISSUE TITLE
List year 1 visits and years 2-10 visits

### ISSUE THREAD

**Issue by SimonKrughoff** [LSSTDESC/Twinkles#441]
In order to do the Level 1 reprocessing workflow we will build a template with the year 1 data and difference the remaining years against that year one data.  This means we need different input files for the coadd building and differencing steps.  I think Rahul signed up to do this, but could be wrong.

**Comment by drphilmarshall** [comment]
I think this is something @rbiswas4 can do straightforwardly. How do we manage these visit lists, by the way? Are they checked in somewhere in this Twinkles repo, or just emailed to Tony and then written about? Or is the code that makes the selection checked in? Probably this latter option is a good idea, in case we all get hit by buses.

**Comment by rbiswas4** [comment]
@SimonKrughoff I am happy to do whatever is required, but I am trying to understand what are the contents of the input files you are seeking: Is it obsHistIDs for the year 1 runs that have already been done (ie. not part of long jobs, and failed jobs?) and non year 1 runs for science images?


@drphilmarshall In previous cases I checked [code](https://github.com/LSSTDESC/Twinkles/blob/master/bin/get_twinkles_visits.py) into the Twinkles repo.

**Comment by SimonKrughoff** [comment]
@rbiswas4 I think obsHistIDs for year 1 in one file and all the rest in another file would be good enough.

**Comment by rbiswas4** [comment]
@SimonKrughoff You want the ones that failed removed correct?

**Comment by SimonKrughoff** [comment]
@rbiswas4 I don't know what "ones" and "failed" are in this context.

**Comment by rbiswas4** [comment]
@SimonKrughoff The split files are Twinkles_1.3_first_year.csv and Twinkles_1.3_other_years.csv in the zip file


[splitvisits.zip](https://github.com/LSSTDESC/Twinkles/files/795531/splitvisits.zip)

**Comment by drphilmarshall** [comment]
Thanks, Rahul!

I count
```

    2661 Twinkles_1.3_first_year.csv

   21495 Twinkles_1.3_other_years.csv

```

which looks about right. Deep drilling fields, eh? So many visits.

**Comment by rbiswas4** [comment]
Right. All of the failed visits were in the last 9 years so if none of our runs had crashed we would have 21514 in the last file.

**Comment by SimonKrughoff** [comment]
@rbiswas4 why would we not just include all the ids?  I understand some crashed, but I'd rather fix that than leave them off the list.

**Comment by rbiswas4** [comment]
OK here is your list of obsHistIDs without removing failures.
[splitvisits.zip](https://github.com/LSSTDESC/Twinkles/files/797361/splitvisits.zip)

**Comment by rbiswas4** [comment]
I think this is closed. If there is something left, please let me know.
