### ISSUE TITLE
Have visits for different Twinkles data releases

### ISSUE THREAD

**Issue by rbiswas4** [LSSTDESC/Twinkles#454]
LSST is supposed to provide data releases at pre-defined points of time. 
For Twinkles 1.3 processing, we would like to emulate such data releases. Provide a list of visits in each such emulated data release.  We will use a slightly different numbering scheme (from LSST, where DR1 is 6 months, DR2 is 1 year etc.). We need files giving us 2 lists (a list of visits for yearly releases, and coadds):
          yearly release   coadds
TDR1 : Year 1               1
TDR2: Year 2               1, 2
TDR3: Year 3               1, 2, 3 
TDR4: Year 4               1, 2, 3, 4
TDR5: Year 5               1, 2, 3, 4, 5
TDR6: Year 6               1, 2, 3, 4, 5, 6
TDR7: Year 7                1, 2, 3, 4, 5, 6, 7
TDR8: Year 8               1, 2, 3, 4, 5, 6, 7, 8
TDR9: Year 9               1, 2, 3, 4, 5, 6, 7, 8, 9  
TDR10: Year 10            1, 2, 3, 4, 5, 6, 7, 8, 9, 10

@drphilmarshall could you please confirm this is what we would like?

**Comment by drphilmarshall** [comment]
See notes in #456 for the final visit selection.
