### ISSUE TITLE
Fix AGN SED problem for DC2

### ISSUE THREAD

**Issue by jbkalmbach** [LSSTDESC/Twinkles#459]
In the draft LSST DESC note for Twinkles 1 I discovered a problem with the magnitudes of AGN SEDs where they were being calculated and matched with the rest frame SEDs instead of the redshifted SEDs. This needs to be fixed before using the sprinkler in DC2.

**Comment by cwwalter** [comment]
Could you also put an issue in the DC2 repo since not everyone follows here?

**Comment by jbkalmbach** [comment]
For sure. We are currently hammering out a list of issues that we will add to DC2 to upgrade the Sprinkler and will add it as an epic issue in DC2.

**Comment by jbkalmbach** [comment]
Fixed in #462
