### ISSUE TITLE
Minimum wavelength in SED files for lensed supernovae

### ISSUE THREAD

**Issue by jchiang87** [LSSTDESC/Twinkles#470]
@jbkalmbach The SEDs in the `specFileGLSN*` files all start at 300nm, so that when they are redshifted, the lower bound is greater than the minimum LSST bandpass wavelength.  When imSim tries to resample the GLSN SEDs into the LSST bandpass, it inserts nans for the uncovered wavelengths, and galsim subsequently crashes when fed a flux with a nan value.   The `specFilesGLSN*` files need to start at a shorter wavelength, e.g., 30nm as for the `specFileSN*` files.

**Comment by rbiswas4** [comment]
There is protection for this kind of problem in `SNObject`. It would be good to use that.
