### ISSUE TITLE
sprinkler won't produce unique galaxy_ids in DC2

### ISSUE THREAD

**Issue by danielsf** [LSSTDESC/Twinkles#474]
For Twinkles, we used this line of code to produce unique identifiers for the sprinkled objects

https://github.com/LSSTDESC/Twinkles/blob/master/python/desc/twinkles/sprinkler.py#L338

This line assumes that all `galtileid`s have the same number of significant bits.  That will not necessarily be true in DC2 where `galtileid` is replaced by `galaxy_id`, and `galaxy_id==1` is a legal value.  This could cause collisions between sprinkled `galaxy_id`s and unsprinkled `galaxy_id`s.  We need to make sure that does not happen.

**Comment by danielsf** [comment]
Also, we should think about whether this line

https://github.com/LSSTDESC/Twinkles/blob/master/python/desc/twinkles/sprinkler.py#L186

is going to produce useful seeds, now that `galtileid==galaxy_id` can be less than `10**8`

**Comment by jbkalmbach** [comment]
After discussion with @danielsf, I will replace the `TWINKLES_ID` line that gets the image number added to it by a unique number for each Twinkles system + image combination to bring the added numbers down from 10000 to ~5000. We should have enough buffer with 5000*1024*1e11 to stay under the 9e18 integer limit.

**Comment by jbkalmbach** [comment]
Since this will require some editing of the sprinkler code I want to make sure the validation code gets merged before changing anything. After that I will update this.

**Comment by jbkalmbach** [comment]
This is no longer waiting on validation code but it is waiting on final DC2 galaxies.

**Comment by jbkalmbach** [comment]
Closed in #480
