### ISSUE TITLE
Write notebook to document steps need to generate input for producing lensed images

### ISSUE THREAD

**Issue by jbkalmbach** [LSSTDESC/Twinkles#481]
@linan7788626 needs catalogs with information on the hosts of our lensed AGN and SNe. We need to be able to replicate and document the steps to produce these catalogs. The goal of this issue is a notebook that generates these catalogs from the information in the `data` folder.

**Comment by linan7788626** [comment]
The lensed hosts for AGNs and SNe are saved here
https://portal.nersc.gov/project/hacc/nanli/codes_for_lensed_hosts_20181013.tar

We will decide whether this issue can be closed after the discussion with Matt.

**Comment by jbkalmbach** [comment]
Closed by 488
