### ISSUE TITLE
Realistic lens galaxies from Illustris

### ISSUE THREAD

**Issue by linan7788626** [LSSTDESC/Twinkles#52]
Since we can now make `PhoSim` images using images of galaxies in FITS format, we can think of using the Illustris simulations to give us both the mass distribution and light distribution of some realistic massive galaxies. The [Illustris data release paper](http://arxiv.org/pdf/1504.00362v2.pdf) and also [this interesting early strong lens analysis paper](http://arxiv.org/pdf/1507.07937.pdf) both promise a mock strong lens catalog "soon". We should look at this, to see if we can match the OM10 lenses by {sigma,zd,ellipticity} to some massive Illustris galaxies, and then, starting from the OM10 image positions, compute new image positions and time delays using the Illustris mass distribution - and then we can use the Illustris light distribution in the `PhoSim` run.

This approach will solve the problems of 1) the OM10 model inconsistency, and 2) needing the lens light distribution.

Before the Illustris catalog is released, we could mock this up with an NFW profile DM distribution plus a De Vaucoleurs light distribution, with parameters chosen in some simple way...

**Comment by drphilmarshall** [comment]
Hi @linan7788626 ! Can you please give me a very short update on this work, post Hack Day? I thought your Illustris 3 results were very promising, did you try the higher resolution systems?  Some quick links to your Hack Day results and others would be very helpful here, too.

We'll need to make a decision about whether or not to try and build realistic galaxy images into Twinkles 1 fairly soon: it's not something we have discussed much yet, outside the SL group. I don't know how familiar @rbiswas4 @danielsf and @jbkalmbach are with pasting in images so that PhoSim can draw from them, they might be able to comment on the feasibility of adding Einstein Rings to the Twinkles sims. Thanks! :-)

**Comment by linan7788626** [comment]
Hi @drphilmarshall ,

Sorry for my Silence, I am in China now, the network here is terribly unstable because of "the Fucking Great Firewall".  I post some description of the progress of this project below. and I will organize all updates better when I am back in the US (about 2 weeks later).

>Since we can now make PhoSim images using images of galaxies in FITS format, we can think of using the Illustris simulations to give us both the mass distribution and light distribution of some realistic massive galaxies. The Illustris data release paper and also this interesting early strong lens analysis paper both promise a mock strong lens catalog "soon". 

- [x] We can match the OM10 lenses by {sigma,zd,ellipticity} to some massive Illustris galaxies, and then, starting from the OM10 image positions, compute new image positions and time delays using the Illustris mass distribution. [Click here](https://github.com/linan7788626/Arc_Finding_CNN/issues/23) 

- [x] We can use the Illustris light distribution in the PhoSim run. [Click here](https://github.com/linan7788626/hackday_03112016/issues/2)

- [x] We could mock this up with an NFW profile DM distribution plus a De Vaucoleurs light distribution, with parameters chosen in some simple way. Actually, We are using SIE model, and the fundamental plane to calculate parameters (including {I_e, R_e, Ellip, Orientation}) of a De Vaucoleurs light distribution. This work has been done, I will upload the codes later. 

Future work: 
* [ ] Try "the higher resolution systems" when I am back in the US, because the network here is too slow to download ~1.0 T  files. 
* [ ] Try Illustris snapshots at higher redshift. 
* [ ] Find a relative easier way to produce the light of lenses. [Sunrise](https://bitbucket.org/lutorm/sunrise) might be like "using a sledgehammer to crack a nut" for lensing simulations only.

**Comment by zhanhu** [comment]
Watch your language. Be mature.

**Comment by linan7788626** [comment]
@zhanhu, apologize for my improper expression, just erase it, and will be careful next time. thanks for your reminding.

**Comment by drphilmarshall** [comment]
Sounds good, @linan7788626 - thanks for the update! Sounds like we should meet up with @jbkalmbach  when you are back, so we can look at the higher resolution Illustris results, and how your code might be used to update the Twinkles lens sprinkler. We'll need to think about how to pass around the simulated image data too, so it can be ingested by PhoSim at SLAC or NERSC. Enjoy the rest of your trip!
