### ISSUE TITLE
Implement part of the cookbook as a Continuous Integration test

### ISSUE THREAD

**Issue by jchiang87** [LSSTDESC/Twinkles#72]
Presumably, the steps from `ingestImages.py...` onwards in the [cookbook](https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/code/twinkles_cookbook.md) (and adding the running of `plot_point_mags.py`) could be crafted in to a single executable and run as an integration test in Jenkins.

Lower level unit tests would also be good to have.

**Comment by SimonKrughoff** [comment]
I think we could even skip ingestImages.py and just start with a minimal input schema similar to the one I tarred up for the cookbook.

**Comment by drphilmarshall** [comment]
@jchiang87 Do we want to resurrect this issue since we'll be working with a stack installed from source at SLAC? You had mentioned wanting to look into Jenkins again.

**Comment by jchiang87** [comment]
I have Jenkins configured to do builds of our repos, and Brian set up a Slack channel for those builds: https://lsstc.slack.com/messages/desc-builds/

I've set up the webhook for pserv, but I need the admins of Twinkle and Monitor to do the same for those repos. @drphilmarshall @jbkalmbach  Could you set those up please?

To do that do
```
Settings -> Integrations & services -> Add service -> Jenkins (GitHub plugin)
```
and then for the Jenkins hook url, enter
```
http://srs.slac.stanford.edu/hudson/github-webhook/
```

**Comment by jchiang87** [comment]
If someone really wants to do this they can either reopen or make a new issue.
